name: CI PR Build/Test

on:
  pull_request:
    branches:
      - "**"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build-test-code:
    uses: ./.github/workflows/build-test-code.yml
